"""Remove tot_views from News table

Revision ID: 0fcf89e47dc1
Revises: 
Create Date: 2024-10-30 01:39:13.370920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcf89e47dc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('tot_remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tot_remarks', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
