"""Added header col to table

Revision ID: 10c2647686d1
Revises: 8ed6b00bfe15
Create Date: 2024-10-23 11:51:09.264497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c2647686d1'
down_revision = '8ed6b00bfe15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('header')

    # ### end Alembic commands ###
