"""added test col

Revision ID: 151e0ab9fd96
Revises: d015a4120abd
Create Date: 2024-09-19 13:30:37.655704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151e0ab9fd96'
down_revision = 'd015a4120abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_me2', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_column('remember_me2')

    # ### end Alembic commands ###
