"""Added is_online, created_at and updated_at

Revision ID: 179c3c2aa3c7
Revises: 3f1e454e6211
Create Date: 2024-09-19 18:08:31.833497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179c3c2aa3c7'
down_revision = '3f1e454e6211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
