"""Add profile data to User table

Revision ID: 2c31ee0c0864
Revises: 
Create Date: 2024-11-02 12:08:02.478918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c31ee0c0864'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('profile_icon', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('profile_icon')
        batch_op.drop_column('country')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
