"""Add new_email column to User table

Revision ID: 676624157681
Revises: 
Create Date: 2024-11-07 12:28:01.382391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676624157681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_email', sa.String(length=75), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_column('new_email')

    # ### end Alembic commands ###
