"""Inital

Revision ID: 8c1f450777fa
Revises: 
Create Date: 2025-01-28 17:55:18.871703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1f450777fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fast_name', sa.String(length=16), nullable=True),
    sa.Column('fast_code', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('profile_icon', sa.String(length=32), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('news_notifications', sa.Boolean(), nullable=False),
    sa.Column('comment_notifications', sa.Boolean(), nullable=False),
    sa.Column('bakery_notifications', sa.Boolean(), nullable=False),
    sa.Column('employee_name', sa.String(length=32), nullable=True),
    sa.Column('roles', sa.String(length=255), nullable=False),
    sa.Column('new_email', sa.String(length=75), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('last_setting_update', sa.String(length=32), nullable=True),
    sa.Column('updated_setting_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('tot_logins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_name'),
    sa.UniqueConstraint('fast_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('authentication_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=75), nullable=True),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bakery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('category', sa.String(length=75), nullable=False),
    sa.Column('program', sa.Integer(), nullable=False),
    sa.Column('nasa', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('vegan', sa.Boolean(), nullable=False),
    sa.Column('lactose_free', sa.Boolean(), nullable=False),
    sa.Column('nutri_score', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=225), nullable=False),
    sa.Column('tags', sa.String(length=225), nullable=False),
    sa.Column('package_type', sa.String(length=75), nullable=True),
    sa.Column('per_package', sa.String(length=75), nullable=True),
    sa.Column('rack_type', sa.String(length=75), nullable=True),
    sa.Column('per_rack', sa.String(length=75), nullable=True),
    sa.Column('defrost_time', sa.String(length=75), nullable=True),
    sa.Column('cooldown_time', sa.String(length=75), nullable=True),
    sa.Column('make_halves', sa.Boolean(), nullable=True),
    sa.Column('contains', sa.String(length=255), nullable=False),
    sa.Column('may_contain', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('search_field', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=100), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.Column('add_update', sa.String(length=20), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=255), nullable=False),
    sa.Column('names', sa.Text(), nullable=False),
    sa.Column('start_hours', sa.Text(), nullable=False),
    sa.Column('end_hours', sa.Text(), nullable=False),
    sa.Column('starts', sa.Text(), nullable=False),
    sa.Column('ends', sa.Text(), nullable=False),
    sa.Column('break_times', sa.Text(), nullable=False),
    sa.Column('work_times', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('header', sa.Text(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('important', sa.Text(), nullable=False),
    sa.Column('grid_cols', sa.Text(), nullable=False),
    sa.Column('grid_rows', sa.Text(), nullable=False),
    sa.Column('info_cols', sa.Text(), nullable=False),
    sa.Column('info_rows', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('seen_by', sa.Text(), nullable=True),
    sa.Column('accepted_by', sa.Text(), nullable=True),
    sa.Column('liked_by', sa.Text(), nullable=True),
    sa.Column('disliked_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('liked_by', sa.Text(), nullable=True),
    sa.Column('disliked_by', sa.Text(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('news')
    op.drop_table('schedule')
    op.drop_table('oauth_states')
    op.drop_table('employees')
    op.drop_table('emails')
    op.drop_table('bakery_items')
    op.drop_table('authentication_tokens')
    op.drop_table('auth')
    # ### end Alembic commands ###
