"""Updated News table

Revision ID: a529dac8adde
Revises: 
Create Date: 2024-10-18 14:57:41.582670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a529dac8adde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('important', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('grid_cols', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('grid_rows', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('info_cols', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('info_rows', sa.Text(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.alter_column('author',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=75),
               existing_nullable=False)
        batch_op.drop_column('info_rows')
        batch_op.drop_column('info_cols')
        batch_op.drop_column('grid_rows')
        batch_op.drop_column('grid_cols')
        batch_op.drop_column('important')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
