"""Set display_name in User table unique=True

Revision ID: f9a288109345
Revises: 2c31ee0c0864
Create Date: 2024-11-02 21:06:41.331963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a288109345'
down_revision = '2c31ee0c0864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_display_name", ['display_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_constraint("uq_display_name", type_='unique')

    # ### end Alembic commands ###
