"""Chaned viewed and accepted in News table

Revision ID: ffaa3b99407f
Revises: f91f70422795
Create Date: 2024-10-24 13:18:26.903376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffaa3b99407f'
down_revision = 'f91f70422795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_by', sa.Text(), nullable=True))
        batch_op.drop_column('tot_accepted')
        batch_op.drop_column('tot_views')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tot_views', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tot_accepted', sa.INTEGER(), nullable=False))
        batch_op.drop_column('accepted_by')

    # ### end Alembic commands ###
