import os.path

from config.settings import (BREAD_IMAGES_FOLDER, SMALL_BREAD_IMAGES_FOLDER,
                             STOKBROOD_IMAGES_FOLDER, SAVORY_IMAGES_FOLDER,
                             PASTRY_IMAGES_FOLDER, SWEETS_IMAGES_FOLDER)


def get_lp_bread_dict() -> dict:
    data = {
        "Petit Beurre": {
            "category": "LP",
            "program": 1,
            "nasa": 815838,
            "price": 1.79,
            "type": ["Desem", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Roomboter", "Vloerbrood"],
            "rack_type": "Rack",
            "per_rack": "3 * 2",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Rogge", "Tarwe"],
            "may_contain": ["Sesamzaad", "Soja"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "petit_beurre.png"),
        },
        "Petit Cereales": {
            "category": "LP",
            "program": 1,
            "nasa": 815837,
            "price": 1.79,
            "type": ["Desem", "Bruin", "Meergranen", "Vloerbrood"],
            "tags": ["Desem", "Bruin", "Meergranen", "Vloerbrood", "Roomboter",
                     "Lijnzaad", "Zonnebloempitten", "Havervlokken"],
            "rack_type": "Rack",
            "per_rack": "3 * 2",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Gerst", "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "petit_cereales.png"),
        },
        "Petit Volkoren": {
            "category": "LP",
            "program": 1,
            "nasa": 607181,
            "price": 2.39,
            "type": ["Desem", "Volkoren", "Tarwe-Rogge", "Vloerbrood"],
            "tags": ["Desem", "Volkoren", "Tarwe-Rogge", "Roomboter",
                     "Maisgries", "Maanzaad", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "4 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Gerst", "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "petit_volkoren.png"),
        },
        "Petit Tarwe Rogge": {
            "category": "LP",
            "program": 1,
            "nasa": 684266,
            "price": 2.19,
            "type": ["Desem", "Wit", "Roggebloem"],
            "tags": ["Desem", "Wit", "Roggebloem", "Gekiemde Rogge"],
            "rack_type": "Rack",
            "per_rack": "4 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Gerst", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "petit_tarwe_rogge.png"),
        },
        "Petit Kampioentje": {
            "category": "LP",
            "program": 1,
            "nasa": 16224,
            "price": 2.29,
            "type": ["Desem", "Wit", "Meergranen", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Meergranen", "Vloerbrood", "Rogge", "Speltdesem",
                     "Lijnzaad", "Maanzaad", "Sesamzaad", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst", "Haver",
                         "Spelt", "Rogge", "Tarwe"],
            "may_contain": ["Melk, Soja, Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "petit_kampioentje.png"),
        },
        "L&P Spelt": {
            "category": "LP",
            "program": 2,
            "nasa": 815834,
            "price": 3.19,
            "type": ["Desem", "Spelt", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Spelt", "Wit", "Vloerbrood",
                     "Lijnzaad", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Spelt"],
            "may_contain": ["Melk, Sesamzaad, Soja, Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_spelt.png"),
        },
        "L&P Spelt Volkoren": {
            "category": "LP",
            "program": 2,
            "nasa": 742143,
            "price": 3.19,
            "type": ["Desem", "Spelt", "Volkoren", "Vloerbrood"],
            "tags": ["Desem", "Spelt", "Volkoren", "Vloerbrood",
                     "Lijnzaad", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Spelt"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_spelt_volkoren.png"),
        },
        "L&P Meergranen": {
            "category": "LP",
            "program": 2,
            "nasa": 84021,
            "price": 2.89,
            "type": ["Desem", "Bruin", "Vloerbrood"],
            "tags": ["Desem", "Bruin", "Vloerbrood", "Tarwe", "Rogge", "Gierst",
                     "Sesamzaad", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst", "Spelt",
                         "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_meergranen.png"),
        },
        "L&P Meerzaden": {
            "category": "LP",
            "program": 2,
            "nasa": 815835,
            "price": 3.09,
            "type": ["Desem", "Wit", "Meerzaden", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Meerzaden", "Vloerbrood", "Lijnzaad", "Maanzaad",
                     "Sesamzaad", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Soja", "Tarwe"],
            "may_contain": ["Melk", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_meerzaden.png"),
        },
        "L&P Emmer": {
            "category": "LP",
            "program": 2,
            "nasa": 697853,
            "price": 3.19,
            "type": ["Desem", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Vloerbrood", "Emmer-Tarwe", "Lijnzaad",
                     "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Sesamzaad", "Soja", "Gerst", "Haver",
                            "Lactose", "Lupine", "Rogge", "Amandel", "Hazelnoot",
                            "Pistachenoot", "Walnoot", "Sesamzaad", "Soja", "Gerst",
                            "Haver", "Lactose", "Lupine", "Rogge", "Amandel",
                            "Hazelnoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_emmer.png"),
        },
        "L&P Spelt Boekweit": {
            "category": "LP",
            "program": 2,
            "nasa": 682921,
            "price": 3.19,
            "type": ["Desem", "Spelt", "Boekweit", "Vloerbrood"],
            "tags": ["Desem", "Spelt", "Boekweit", "Vloerbrood", "Maanzaad",
                     "Sesamzaad"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Spelt"],
            "may_contain": ["Melk", "Noten", "Soja", "Gerst", "Haver", "Lactose",
                            "Lupine", "Rogge", "Hazelnoot", "Pistachenoot",
                            "Walnoot", "Tarwe"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_spelt_boekweit.png"),
        },
        "L&P Pompoen": {
            "category": "LP",
            "program": 2,
            "nasa": 742142,
            "price": 3.19,
            "type": ["Desem", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Vloerbrood", "Pompoenpitten"],
            "rack_type": "Rack",
            "per_rack": "2 * 2",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Sesamzaad", "Soja", "Gerst", "Haver",
                            "Lactose", "Lupine", "Amandel", "Hazelnoot",
                            "Macadamianoot", "Paranoot", "Pistachenoot",
                            "Walnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_pompoen.png"),
        },
        "L&P San Francisco": {
            "category": "LP",
            "program": 2,
            "nasa": 688459,
            "price": 3.19,
            "type": ["Desem", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Vloerbrood"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Sesamzaad", "Soja", "Haver",
                            "Lactose", "Lupine", "Rogge", "Amandel",
                            "Hazelnoot", "Macadamianoot", "Paranoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_san_francisco.png"),
        },
        "L&P Nederlands Blond": {
            "category": "LP",
            "program": 2,
            "nasa": 580687,
            "price": 3.19,
            "type": ["Desem", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Vloerbrood"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Sesamzaad", "Soja", "Gerst",
                            "Haver", "Lactose", "Lupine", "Rogge", "Amandel",
                            "Hazelnoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_nederlands_blond.png"),
        },
        "L&P Winterblond": {
            "category": "LP",
            "program": 2,
            "nasa": 21709,
            "price": 3.19,
            "type": ["Desem", "Wit", "Vloerbrood"],
            "tags": ["Desem", "Wit", "Vloerbrood", "Nederlands Graan"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Soja", "Gerst", "Haver",
                            "Lactose", "Lupine", "Rogge", "Amandel",
                            "Hazelnoot", "Macadamianoot", "Paranoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_winterblond.png"),
        },
        "L&P Zonne Rogge": {
            "category": "LP",
            "program": 2,
            "nasa": 21710,
            "price": 3.19,
            "type": ["Desem", "Vloerbrood"],
            "tags": ["Desem", "Vloerbrood", "Rogge", "Zonnebloempitten", "Karwijzaad"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": "90 min",
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Sesamzaad", "Soja", "Gerst",
                            "Haver", "Lactose", "Lupine", "Amandel",
                            "Hazelnoot", "Macadamianoot", "Paranoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "lp_zonne_rogge.png"),
        },
    }
    return data


def get_stevig_bread_dict() -> dict:
    data = {
        "Stevig Spelt": {
            "category": "Stevig",
            "program": 1,
            "nasa": 804204,
            "price": 2.99,
            "type": ["Spelt", "Bruin", "Stevig"],
            "tags": ["Spelt", "Bruin", "Stevig"],
            "rack_type": "Rack",
            "per_rack": "4 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Spelt"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "stevig_spelt.png"),
        },
        "Stevig Donker Meergranen": {
            "category": "Stevig",
            "program": 1,
            "nasa": 788899,
            "price": 2.79,
            "type": ["Meergranen", "Stevig"],
            "tags": ["Meergranen", "Stevig", "Roggemout", "lijnzaad",
                     "zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "4 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Soja", "Gerst",
                         "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "stevig_donker_meergranen.png"),
        },
        "Stevig Grof Volkoren": {
            "category": "Stevig",
            "program": 1,
            "nasa": 824068,
            "price": 2.79,
            "type": ["Stevig"],
            "tags": ["Stevig"],
            "rack_type": "Rack",
            "per_rack": "4 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "stevig_volkoren.png"),
        },
        "Stevig Eiwitrijk": {
            "category": "Stevig",
            "program": 1,
            "nasa": 92887,
            "price": 3.09,
            "type": ["Volkoren", "Meerzaden", "Stevig"],
            "tags": ["Volkoren", "Meerzaden", "Stevig", "Koolhydraat arm",
                     "Koolhydraat verlaagd", "Eiwitrijk"],
            "rack_type": "Rack",
            "per_rack": "4 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Melk", "Sesamzaad", "Glutenbevattende Granen", "Soja",
                         "Gerst", "Haver", "Lactose", "Tarwe"],
            "may_contain": ["Amandel", "Hazelnoot", "Macadamianoot", "Paranoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "stevig_eiwitrijk.png"),
        },

    }
    return data


def get_vloer_bread_dict() -> dict:
    data = {
        "Vloer wit": {
            "category": "Vloer",
            "program": 1,
            "nasa": 688457,
            "price": 2.69,
            "type": ["Wit", "Vloerbrood"],
            "tags": ["Wit", "Vloerbrood", "Nederlands graan"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": True,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Soja", "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Lupine", "Amandel", "Hazelnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "vloer_wit.png"),
        },
        "Vloer Meergranen": {
            "category": "Vloer",
            "program": 1,
            "nasa": 688460,
            "price": 2.69,
            "type": ["Bruin", "Meergranen", "Vloerbrood"],
            "tags": ["Meergranen", "Vloerbrood", "Nederlands graan", "Tarwe", "Rogge",
                     "Gerst", "Haver", "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": True,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Gerst", "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Noten", "Sesamzaad", "Soja", "Lactose",
                            "Amandel", "Hazelnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "vloer_meergranen.png"),
        },
        "Vloer Volkoren": {
            "category": "Vloer",
            "program": 1,
            "nasa": 688461,
            "price": 2.69,
            "type": ["Volkoren", "Vloerbrood"],
            "tags": ["Volkoren", "Vloerbrood", "Nederlands graan", "Maisgries",
                     "Maanzaad", "Sesamzaad"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": True,
            "vegan": False,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst", "Rogge",
                         "Tarwe"],
            "may_contain": ["Melk", "Noten", "Soja", "Lactose", "Lupine",
                            "Amandel", "Hazelnoot"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "vloer_volkoren.png"),
        },
        "Vloer Waldkorn": {
            "category": "Vloer",
            "program": 1,
            "nasa": 657657,
            "price": 2.69,
            "type": ["Volkoren", "Meergranen", "Vloerbrood"],
            "tags": ["Volkoren", "Meergranen", "Vloerbrood", "Waldkorn"],
            "rack_type": "Rack",
            "per_rack": "3 * 1",
            "defrost_time": None,
            "cooldown_time": "90 min",
            "make_halves": True,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Soja", "Gerst",
                         "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Lactose"],
            "image": os.path.join(BREAD_IMAGES_FOLDER,
                                  "vloer_waldkorn.png"),
        },
    }
    return data


def get_small_bread_dict() -> dict:
    data = {
        "Kaiserbroodje Wit": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 571395,
            "price": 0.29,
            "type": ["Wit", "Kleinbrood"],
            "tags": ["Wit", "Kleinbrood"],
            "rack_type": "Rack",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Rogge", "Tarwe"],
            "may_contain": ["Sesamzaad", "Gerst", "Haver", "Spelt"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "kaiserbroodje_wit.png"),
        },
        "Kaiserbroodje Volkoren": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 728700,
            "price": 2.69,
            "type": ["Volkoren", "Kleinbrood"],
            "tags": ["Volkoren", "Kleinbrood"],
            "rack_type": "Rack",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Spelt", "Rogge", "Tarwe"],
            "may_contain": ["Sesamzaad", "Haver"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "kaiserbroodje_volkoren.png"),
        },
        "Schnittbroodje Bruin": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 843629,
            "price": 0.25,
            "type": ["Bruin"],
            "tags": ["Bruin"],
            "rack_type": "Rack",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Tarwe"],
            "may_contain": ["Sesamzaad", "Haver", "Spelt", "Rogge"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "schnittbroodje_bruin.png"),
        },
        "Schnittbroodje Wit": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 636608,
            "price": 0.25,
            "type": ["Wit"],
            "tags": ["Wit"],
            "rack_type": "Rack",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Sesamzaad"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "schnittbroodje_wit.png"),
        },
        "Pistolet Wit": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 508205,
            "price": 0.25,
            "type": ["Wit"],
            "tags": ["Wit"],
            "rack_type": "Rack",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Gerst", "Haver", "Spelt", "Rogge"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER, "pistolet_wit.png"),
        },
        "Pistolet Bruin": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 508204,
            "price": 0.25,
            "type": ["Bruin"],
            "tags": ["Bruin"],
            "rack_type": "Rack",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Gerst", "Haver", "Spelt", "Rogge"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "pistolet_bruin.png"),
        },
        "Tijgerbol": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 77660,
            "price": 0.35,
            "type": ["Bruin"],
            "tags": ["Bruin", "Rijstebloem"],
            "rack_type": "Rack",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Melk", "Sesamzaad", "Soja", "Gerst", "Haver", "Spelt",
                            "Lactose", "Rogge"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "tijgerbol.png"),
        },
        "Italiaanse Bol": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 89629,
            "price": 0.79,
            "type": ["Wit"],
            "tags": ["Wit", "Kruiden", "Olijfolie"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Sesamzaad", "Soja", "Lactose",
                            "Lupine", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Macadamianoot", "Pecannoot", "Paranoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "italiaanse_bol.png"),
        },
        "Triangel Meergranen": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 567800,
            "price": 0.69,
            "type": ["Bruin", "Meergranen"],
            "tags": ["Bruin", "Meergranen", "Zaden", "Pitten"],
            "rack_type": "Rack",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Sesamzaad", "Soja", "Lactose",
                            "Lupine", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Macadamianoot", "Pecannoot", "Paranoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "triangel_meergranen.png"),
        },
        "Ciabatta Rozijn": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 851438,
            "price": 0.69,
            "type": ["Wit"],
            "tags": ["Wit", "Rozijnen", "Krenten"],
            "rack_type": "Rack",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Sesamzaad", "Soja", "Mosterd",
                            "Gerst", "Haver", "Spelt", "Lactose", "Amandel",
                            "Cashewnoot", "Hazelnoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "ciabatta_rozijn.png"),
        },
        "Kaas Ruitbroodje": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 704037,
            "price": 0.39,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Sesamzaad"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "kaas_ruitbroodje.png"),
        },
        "Bakkersbroodje Bastille": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20141,
            "price": 0.00,
            "type": ["Volkoren", "Meerzaden"],
            "tags": ["Volkoren", "Meerzaden"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Soja", "Gerst",
                         "Rogge", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Haver", "Lactose", "Amandel",
                            "Hazelnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_bastille.png"),
        },
        "Bakkersbroodje Boulogne": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20142,
            "price": 0.00,
            "type": ["Volkoren", "Meerzaden"],
            "tags": ["Volkoren", "Meerzaden"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Soja", "Gerst",
                         "Haver", "Tarwe"],
            "may_contain": ["Melk", "Lactose"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_boulogne.png"),
        },
        "Bakkersbroodje Everything": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20145,
            "price": 0.00,
            "type": ["Wit", "Meerzaden"],
            "tags": ["Wit", "Meerzaden"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Rogge", "Tarwe"],
            "may_contain": ["Soja", "Lupine"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_everything.png"),
        },
        "Bakkersbroodje Cornflakes": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20144,
            "price": 0.00,
            "type": ["Wit"],
            "tags": ["Wit", "Mais", "Cornflakes"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Haver", "Spelt", "Rogge", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_cornflakes.png"),
        },
        "Bakkersbroodje Matisse": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20143,
            "price": 0.00,
            "type": ["Bruin", "Meerzaden"],
            "tags": ["Bruin", "Meerzaden", "Brouwgraan"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst", "Tarwe"],
            "may_contain": ["Melk", "Soja", "Lactose"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_matisse.png"),
        },
        "Bakkersbroodje Salt Pepper": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20134,
            "price": 0.00,
            "type": ["Wit"],
            "tags": ["Wit", "Mais", "Peper", "Zout"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Gerst", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Sesamzaad", "Soja", "Selderij",
                            "Mosterd", "Haver", "Spelt", "Rogge", "Amandel",
                            "Hazelnoot", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_salt_pepper.png"),
        },
        "Bakkersbroodje Spelt": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 820315,
            "price": 0.00,
            "type": ["Spelt", "Wit"],
            "tags": ["Spelt", "Wit"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Melk", "Lactose",
                         "Spelt", "Sesamzaad"],
            "may_contain": ["Tarwe", "Eieren", "Mosterd", "Selderij", "Soja", "Walnoot",
                            "Hazelnoot", "Amandel", "Noten", "Rogge", "Gerst"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_spelt.png"),
        },
        "Bakkersbroodje Triomph": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 28612,
            "price": 0.00,
            "type": ["Wit", "Meerzaden"],
            "tags": ["Wit", "Meerzaden"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Soja", "Gerst", "Rogge", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Sesamzaad", "Haver", "Lactose",
                            "Amandel", "Hazelnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "bakkersbroodje_triomph.png"),
        },
        "Carre Blanc": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20135,
            "price": 0.89,
            "type": ["Desem", "Wit"],
            "tags": ["Desem", "Wit"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Rogge", "Tarwe"],
            "may_contain": ["Sesamzaad", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "carre_blanc.png"),
        },
        "Carre Kampioentje": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20138,
            "price": 1.09,
            "type": ["Wit"],
            "tags": ["Wit"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Tarwe", "Rogge", "Glutenbevattende Granen"],
            "may_contain": [],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "carre_kampioentje.png"),
        },
        "Carre Meerzaden": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20137,
            "price": 0.99,
            "type": ["Desem", "Wit", "Meerzaden"],
            "tags": ["Desem", "Wit", "Meerzaden"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst",
                         "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Soja", "Mosterd", "Walnoot"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "carre_meerzaden.png"),
        },
        "Carre Pompoen": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20135,
            "price": 0.99,
            "type": ["Desem", "Wit"],
            "tags": ["Desem", "Wit", "Pompoen"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst",
                         "Rogge", "Tarwe"],
            "may_contain": ["Noten", "Haver", "Spelt", "Lactose"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "carre_pompoen.png"),
        },
        "Carre Walnoot": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 20139,
            "price": 1.29,
            "type": ["Desem", "Wit", "Rogge"],
            "tags": ["Desem", "Wit", "Rogge", "Rozijnen", "Krenten", "Walnoot"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Soja", "Gerst", "Rogge",
                         "Walnoot", "Tarwe"],
            "may_contain": ["Sesamzaad", "Mosterd", "Haver", "Spelt", "Lactose"],
            "image": os.path.join(SMALL_BREAD_IMAGES_FOLDER,
                                  "carre_walnoot.png"),
        },
    }

    return data


def get_savory_dict() -> dict:
    data = {
        "Focaccia Pepperoni": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 694744,
            "price": 1.39,
            "type": ["Wit"],
            "tags": ["Wit", "Pepperoni", "Kaas", "Tomaat"],
            "rack_type": "Plate",
            "per_rack": "6 * 2",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Mosterd",
                         "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Sesamzaad", "Soja", "Selderij", "Rogge"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "foccacia_pepperoni.png"),
        },
        "Foccacia Mozzarella": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 578991,
            "price": 0.89,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas", "Tomaat", "Basilicum"],
            "rack_type": "Plate",
            "per_rack": "6 * 2",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Sesamzaad", "Soja", "Selderij",
                            "Mosterd", "Rogge"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "foccacia_mozzarella.png"),
        },
        "Kip Paprikabroodje": {
            "category": "Kleinbrood",
            "program": 3,
            "nasa": 854299,
            "price": 1.99,
            "type": ["Wit"],
            "tags": ["Wit", "Kip", "Tomaat", "Kaas", "Paprika"],
            "rack_type": "Plate",
            "per_rack": "3 * 3",
            "defrost_time": None,
            "cooldown_time": "15 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Rogge", "Tarwe"],
            "may_contain": [],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kip_paprikabroodje.png"),
        },
        "Petit Croissant": {
            "category": "Kleinbrood",
            "program": 5,
            "nasa": 20136,
            "price": 0.99,
            "type": ["Wit"],
            "tags": ["Wit", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "45 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Sesamzaad", "Soja", "Amandel", "Hazelnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "petit_croissant.png"),
        },
        "Chocoladebroodje": {
            "category": "Kleinbrood",
            "program": 5,
            "nasa": 600047,
            "price": 0.55,
            "type": ["Wit"],
            "tags": ["Wit", "Chocolade"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Haver", "Amandel", "Hazelnoot",
                            "Pecannoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "chocoladebroodje.png"),
        },
        "Maple Pecan Vlechtbroodje": {
            "category": "Kleinbrood",
            "program": 5,
            "nasa": 534105,
            "price": 0.69,
            "type": ["Wit"],
            "tags": ["Wit", "Maple", "Pecan", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Haver", "Amandel", "Hazelnoot",
                            "Pecannoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "maple_pecan_vlechtbroodje.png"),
        },
        "Koffiebroodje": {
            "category": "Kleinbrood",
            "program": 5,
            "nasa": 573784,
            "price": 0.59,
            "type": ["Wit"],
            "tags": ["Wit", "Rozijnen"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Soja", "Amandel", "Hazelnoot",
                            "Pecannoot", "Walnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "koffiebroodje.png"),
        },
        "Kaasstengel": {
            "category": "Kleinbrood",
            "program": 5,
            "nasa": 573784,
            "price": 0.59,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "2 * 5",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Gerst", "Khorasan", "Haver", "Spelt", "Rogge"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kaasstengel.png"),
        },
        "Kaassnack": {
            "category": "Kleinbrood",
            "program": 5,
            "nasa": 619196,
            "price": 0.00,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Soja", "Selderij",
                            "Mosterd", "Gerst", "Haver", "Spelt", "Lupine",
                            "Rogge", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Macadamianoot", "Pecannoot", "Paranoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kaassnack.png"),
        },
        "Kaneelbroodje": {
            "category": "Kleinbrood",
            "program": 6,
            "nasa": 81026,
            "price": 0.59,
            "type": ["Wit"],
            "tags": ["Wit", "Kaneel"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Sesamzaad", "Soja", "Selderij",
                            "Mosterd", "Lactose", "Rogge"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kaneelbroodje.png"),
        },
        "Luxe Croissant": {
            "category": "Kleinbrood",
            "program": 6,
            "nasa": 833035,
            "price": 0.99,
            "type": ["Wit"],
            "tags": ["Wit", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Amandel", "Hazelnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "luxe_croissant.png"),
        },
        "Praline Croissant": {
            "category": "Kleinbrood",
            "program": 6,
            "nasa": 584623,
            "price": 1.29,
            "type": ["Wit"],
            "tags": ["Wit", "Chocolade", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Noten", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Amandel", "Hazelnoot", "Tarwe"],
            "may_contain": ["Eieren", "Gerst", "Spelt", "Rogge", "Pecannoot",
                            "Pistachenoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "praline_croissant.png"),
        },
        "Kaas Croissant": {
            "category": "Kleinbrood",
            "program": 6,
            "nasa": 817859,
            "price": 0.89,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Soja", "Gerst", "Spelt", "Rogge",
                            "Amandel", "Hazelnoot", "Pecannoot", "Pistachenoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kaas_croissant.png"),
        },
        "Ham Kaas Croissant": {
            "category": "Kleinbrood",
            "program": 6,
            "nasa": 46570,
            "price": 1.89,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas", "Ham", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Soja", "Gerst", "Spelt",
                            "Rogge", "Amandel", "Hazelnoot", "Pecannoot",
                            "Pistachenoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "ham_kaas_croissant.png"),
        },
        "Frikandelbroodje": {
            "category": "Kleinbrood",
            "program": 8,
            "nasa": 511298,
            "price": 0.95,
            "type": ["Wit"],
            "tags": ["Wit", "Kip", "Varken", "Curry"],
            "rack_type": "Plate",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Soja", "Selderij", "Mosterd",
                            "Gerst", "Haver", "Lupine", "Rogge", "Amandel",
                            "Macadamianoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "frikandelbroodje.png"),
        },
        "Saucijzenbroodje": {
            "category": "Kleinbrood",
            "program": 8,
            "nasa": 529691,
            "price": 0.95,
            "type": ["Wit"],
            "tags": ["Wit", "Varken", "Rund"],
            "rack_type": "Plate",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": [],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "saucijzenbroodje.png"),
        },
        "Kaasbroodje": {
            "category": "Kleinbrood",
            "program": 8,
            "nasa": 28650,
            "price": 0.95,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas"],
            "rack_type": "Plate",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Soja", "Selderij", "Mosterd",
                            "Amandel", "Hazelnoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kaasbroodje.png"),
        },
        "Spinazie Feta Borek": {
            "category": "Kleinbrood",
            "program": 8,
            "nasa": 697199,
            "price": 1.09,
            "type": ["Wit"],
            "tags": ["Wit", "Spinazie", "Feta"],
            "rack_type": "Plate",
            "per_rack": "2 * 5",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Sesamzaad", "Soja", "Mosterd", "Lupine"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "spinazie_feta_borek.png"),
        },
        "Kip Loempia Borek": {
            "category": "Kleinbrood",
            "program": 8,
            "nasa": 719164,
            "price": 1.09,
            "type": ["Wit"],
            "tags": ["Wit", "Kip", "Groente", "Sesamzaad"],
            "rack_type": "Plate",
            "per_rack": "2 * 5",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Sesamzaad", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Eieren", "Soja", "Mosterd", "Lupine"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kip_loempia_borek.png"),
        },
        "Vegan Frikandelbroodje": {
            "category": "Kleinbrood",
            "program": 8,
            "nasa": 697992,
            "price": 1.19,
            "type": ["Wit"],
            "tags": ["Wit", "Curry"],
            "rack_type": "Plate",
            "per_rack": "6 * 2",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Glutenbevattende Granen", "Soja", "Mosterd", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Pinda's", "Selderij",
                            "Gerst", "Haver", "Lactose", "Lupine", "Rogge",
                            "Amandel", "Macadamianoot"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "vegan_frikandelbroodje.png"),
        },
        "Pizzastuk": {
            "category": "Kleinbrood",
            "program": 13,
            "nasa": 539743,
            "price": 1.29,
            "type": ["Wit"],
            "tags": ["Wit", "Kaas"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Sesamzaad", "Gerst", "Haver", "Lupine", "Rogge"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "pizzastuk.png"),
        },
        "Kaas Uienbroodje": {
            "category": "Kleinbrood",
            "program": 13,
            "nasa": 855082,
            "price": 1.29,
            "type": ["Wit"],
            "tags": ["Wit", "Ui", "Kaas"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Sesamzaad", "Gerst", "Haver", "Lupine", "Rogge"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "kaas_uienbroodje.png"),
        },
        "Worstenbroodje": {
            "category": "Kleinbrood",
            "program": 15,
            "nasa": 20136,
            "price": 1.29,
            "type": ["Wit"],
            "tags": ["Wit", "Rund", "Varken"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Sesamzaad", "Soja"],
            "image": os.path.join(SAVORY_IMAGES_FOLDER,
                                  "worstenbroodje.png"),
        },
    }
    return data


def get_stokbrood_dict() -> dict:
    data = {
        "Stokbrood Wit": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 28612,
            "price": 1.39,
            "type": ["Wit"],
            "tags": ["Wit"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Gerst", "Haver", "Spelt", "Rogge"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "stokbrood_wit.png"),
        },
        "Stokbrood Bruin": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 794923,
            "price": 1.39,
            "type": ["Bruin"],
            "tags": ["Bruin"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen, Tarwe"],
            "may_contain": ["Gerst", "Haver", "Spelt", "Rogge"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "stokbrood_bruin.png"),
        },
        "L&P Stokbrood Wit": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 62650,
            "price": 2.29,
            "type": ["Wit"],
            "tags": ["Wit", "Tarwe", "Rogge"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Rogge", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Haver", "Spelt", "Amandel",
                            "Cashewnoot", "Hazelnoot", "Walnoot"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "lp_stokbrood_wit.png"),
        },
        "L&P Stokbrood Spelt": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 728699,
            "price": 2.29,
            "type": ["Spelt", "Wit"],
            "tags": ["Spelt", "Wit", "Tarwe"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Spelt"],
            "may_contain": ["Noten", "Sesamzaad", "Gerst", "Haver", "Rogge",
                            "Amandel", "Cashewnoot", "Hazelnoot", "Walnoot", "Tarwe"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "lp_stokbrood_spelt.png"),
        },
        "L&P Stokbrood Volkoren": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 89354,
            "price": 2.29,
            "type": ["Desem", "Wit", "Volkoren"],
            "tags": ["Desem", "Wit", "Volkoren", "Lijnzaad"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Gerst", "Haver", "Spelt",
                         "Rogge", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Walnoot"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "lp_stokbrood_volkoren.png"),
        },
        "L&P Stokbrood Meergranen": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 62612,
            "price": 2.29,
            "type": ["Desem", "Wit", "Meergranen"],
            "tags": ["Desem", "Wit", "Meergranen", "Lijnzaad", "Sesamzaad",
                     "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst",
                         "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Noten", "Spelt", "Amandel", "Cashewnoot",
                            "Hazelnoot", "Walnoot"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "lp_stokbrood_meergranen.png"),
        },
        "Petit Stokbrood Meerzaden": {
            "category": "Stokbrood",
            "program": 4,
            "nasa": 728697,
            "price": 0.89,
            "type": ["Wit", "Meergranen"],
            "tags": ["Wit", "Meergranen", "Lijnzaad", "Sesamzaad",
                     "Zonnebloempitten"],
            "rack_type": "Rack",
            "per_rack": "1 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": True,
            "contains": ["Sesamzaad", "Glutenbevattende Granen", "Gerst",
                         "Haver", "Rogge", "Tarwe"],
            "may_contain": ["Melk", "Soja", "Spelt", "Lactose"],
            "image": os.path.join(STOKBROOD_IMAGES_FOLDER,
                                  "petit_stokbrood_meerzaden.png"),
        },
    }
    return data


def get_pastry_dict() -> dict:
    data = {
        "Appelflap": {
            "category": "pastry",
            "program": 7,
            "nasa": 529701,
            "price": 0.85,
            "type": ["Wit"],
            "tags": ["Wit", "Appel", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "3 * 4",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Soja", "Selderij", "Mosterd",
                            "Gerst", "Haver", "Lupine", "Rogge", "Amandel",
                            "Macadamianoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "appelflap.png"),
        },
        "Appeltaart": {
            "category": "Pastry",
            "program": 9,
            "nasa": 728697,
            "price": 4.79,
            "type": [],
            "tags": ["Appel", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "3 * 2",
            "defrost_time": None,
            "cooldown_time": "45 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Soja", "Gerst", "Haver",
                            "Rogge", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Macadamianoot", "Pecannoot", "Paranoot", "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "appeltaart.png"),
        },
        "Stoofpeer Notentaart": {
            "category": "Pastry",
            "program": 9,
            "nasa": 20176,
            "price": 5.79,
            "type": [],
            "tags": ["Appel", "Stoofpeer", "Noten", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "3 * 2",
            "defrost_time": None,
            "cooldown_time": "45 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Tarwe", "Glutenbevattende Granen", "Melk", "Cashewnoot",
                         "Pecannoot", "Hazelnoot", "Eieren", "Noten"],
            "may_contain": ["Lupine", "Soja"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "stoofpeer_notentaart.png"),
        },
        "Mini Appeltaart": {
            "category": "Pastry",
            "program": 9,
            "nasa": 600043,
            "price": 1.35,
            "type": [],
            "tags": ["Appel", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "45 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Soja", "Haver", "Spelt", "Amandel",
                            "Cashewnoot", "Hazelnoot", "Macadamianoot", "Pecannoot",
                            "Paranoot", "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "mini_appeltaart.png"),
        },
        "Mini Boterkoek": {
            "category": "Pastry",
            "program": 9,
            "nasa": 808144,
            "price": 1.39,
            "type": [],
            "tags": ["Roomboter"],
            "rack_type": "Rack",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Gerst", "Haver", "Spelt",
                            "Amandel", "Cashewnoot", "Hazelnoot", "Macadamianoot",
                            "Pecannoot", "Paranoot", "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "mini_boterkoek.png"),
        },
        "Gevulde Koek": {
            "category": "Pastry",
            "program": 9,
            "nasa": 511671,
            "price": 0.00,
            "type": [],
            "tags": ["Amandel", "Spijs", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Noten", "Glutenbevattende Granen",
                         "Lactose", "Amandel", "Tarwe"],
            "may_contain": ["Soja", "Gerst", "Haver", "Spelt", "Cashewnoot",
                            "Hazelnoot", "Macadamianoot", "Pecannoot", "Paranoot",
                            "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER, "gevulde_koek.png"),
        },
        "Picolientje": {
            "category": "Pastry",
            "program": 9,
            "nasa": 511669,
            "price": 0.55,
            "type": [],
            "tags": ["Amandel", "Spijs", "Roomboter"],
            "rack_type": "Plate",
            "per_rack": "5 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Noten", "Glutenbevattende Granen",
                         "Lactose", "Amandel", "Tarwe"],
            "may_contain": ["Sesamzaad", "Soja", "Gerst", "Haver", "Spelt",
                            "Cashewnoot", "Hazelnoot", "Macadamianoot",
                            "Pecannoot", "Paranoot", "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "picolientje.png"),
        },
        "Triple Choco Cookie": {
            "category": "Pastry",
            "program": 9,
            "nasa": 603851,
            "price": 1.65,
            "type": [],
            "tags": ["Chocolade"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Selderij", "Mosterd", "Lupine",
                            "Amandel", "Macadamianoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "triple_choco_cookie.png"),
        },
        "Oatmeal Cookie": {
            "category": "Pastry",
            "program": 9,
            "nasa": 816687,
            "price": 1.65,
            "type": [],
            "tags": ["Rozijn", "Cranberry", "Haver"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Selderij", "Mosterd", "Lupine",
                            "Amandel", "Macadamianoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "oatmeal_cookie.png"),
        },
        "Choc Mac Nut Cookie": {
            "category": "Pastry",
            "program": 9,
            "nasa": 791651,
            "price": 1.65,
            "type": [],
            "tags": ["Chocolade", "Macadamia"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Noten", "Glutenbevattende Granen",
                         "Soja", "Lactose", "Macadamianoot", "Tarwe"],
            "may_contain": ["Pinda's", "Selderij", "Mosterd", "Gerst", "Haver",
                            "Spelt", "Lupine", "Rogge", "Amandel", "Cashewnoot",
                            "Hazelnoot", "Macadamianoot", "Pecannoot", "Paranoot",
                            "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "choc_mac_nut_cookie.png"),
        },
        "White Choco BLueberry Muffin": {
            "category": "Pastry",
            "program": 9,
            "nasa": 16039,
            "price": 1.65,
            "type": [],
            "tags": ["Chocolade", "Blueberry"],
            "rack_type": "Plate",
            "per_rack": "4 * 3",
            "defrost_time": None,
            "cooldown_time": "30 min",
            "make_halves": False,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Haver", "Spelt", "Amandel", "Cashewnoot",
                            "Hazelnoot", "Macadamianoot", "Pecannoot", "Paranoot",
                            "Walnoot"],
            "image": os.path.join(PASTRY_IMAGES_FOLDER,
                                  "white_choco_blueberry_muffin.png"),
        },
    }
    return data


def get_sweets_dict() -> dict:
    data = {
        "Crodot": {
            "category": "Sweets",
            "program": 15,
            "nasa": 601912,
            "price": 0.59,
            "type": [],
            "tags": [],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Tarwe"],
            "may_contain": ["Eieren", "Melk", "Noten", "Soja", "Mosterd",
                            "Lactose", "Amandel", "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "crodot.png"),
        },
        "Fruit Sensation Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 82958,
            "price": 1.19,
            "type": [],
            "tags": ["Framboos", "Kwark"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Lactose", "Rogge", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Soja", "Gerst", "Amandel",
                            "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "fruit_sensation_donut.png"),
        },
        "Gesuikerde Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 567803,
            "price": 0.49,
            "type": [],
            "tags": [],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": True,
            "contains": ["Glutenbevattende Granen", "Soja"],
            "may_contain": ["Melk", "Lactose", "Eieren", "Noten", "Hazelnoot",
                            "Amandel"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "gesuikerde_donut.png"),
        },
        "Gedecoreerde Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 573283,
            "price": 0.79,
            "type": [],
            "tags": ["Glazuur"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": True,
            "contains": ["Melk", "Glutenbevattende Granen", "Soja", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Amandel", "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "gedecoreerde_donut.png"),
        },
        "Berlinerbol": {
            "category": "Sweets",
            "program": 15,
            "nasa": 611483,
            "price": 0.55,
            "type": [],
            "tags": ["Framboos", "Aardbei", "Appel"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Soja", "Mosterd", "Gerst",
                            "Haver", "Spelt", "Lupine", "Rogge", "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "berlinerbol.png"),
        },
        "Mini Choclade Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 603851,
            "price": 1.65,
            "type": [],
            "tags": ["Chocolade", "Glazuur"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Soja", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Amandel", "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "mini_choclade_donut.png"),
        },
        "Dubbel Chocolade Muffin": {
            "category": "Sweets",
            "program": 15,
            "nasa": 624331,
            "price": 1.09,
            "type": [],
            "tags": ["Chocolade"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Amandel", "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "dubbel_chocolade_muffin.png"),
        },
        "Vanille Chocolade Muffin": {
            "category": "Sweets",
            "program": 15,
            "nasa": 624332,
            "price": 1.09,
            "type": [],
            "tags": ["Vanille", "Chocolade"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Amandel", "Hazelnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "vanille_chocolade_muffin.png"),
        },
        "Choco Kokos Cake": {
            "category": "Sweets",
            "program": 15,
            "nasa": 640868,
            "price": 0.99,
            "type": [],
            "tags": ["Chocolade", "Kokos"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Soja", "Amandel", "Cashewnoot",
                            "Hazelnoot", "Pecannoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "choco_kokos_cake.png"),
        },
        "Luxe Blueberry Muffin": {
            "category": "Sweets",
            "program": 15,
            "nasa": 640869,
            "price": 1.09,
            "type": [],
            "tags": ["Blueberry"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Sulfieten", "Soja", "Lupine",
                            "Amandel", "Hazelnoot", "Pecannoot", "Pistachenoot",
                            "Walnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "luxe_blueberry_muffin.png"),
        },
        "Rainbow Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 698404,
            "price": 1.19,
            "type": [],
            "tags": ["Chocolade", "Glazuur"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Lactose",
                         "Tarwe"],
            "may_contain": ["Noten", "Hazelnoot", "Pecannoot", "Pistachenoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "rainbow_donut.png"),
        },
        "Marshmellow Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 698420,
            "price": 1.19,
            "type": [],
            "tags": ["Marshmellow", "Glazuur"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Soja", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Mosterd", "Amandel", "Hazelnoot",
                            "Pecannoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "marshmellow_donut.png"),
        },
        "Gevulde Vanille Donut": {
            "category": "Sweets",
            "program": 15,
            "nasa": 729437,
            "price": 0.59,
            "type": [],
            "tags": ["Vanille", "Chocolade", "Glazuur"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Soja", "Lactose", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Amandel", "Hazelnoot", "Pecannoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "gevulde_vanille_donut.png"),
        },
        "Popdots": {
            "category": "Sweets",
            "program": 15,
            "nasa": 740175,
            "price": 0.30,
            "type": [],
            "tags": ["Glazuur"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Melk", "Glutenbevattende Granen", "Soja", "Lactose",
                         "Hazelnoot", "Tarwe"],
            "may_contain": ["Eieren", "Noten", "Amandel"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "popdots.png"),
        },
        "Red Velvet Muffin": {
            "category": "Sweets",
            "program": 15,
            "nasa": 749433,
            "price": 1.69,
            "type": [],
            "tags": ["Roomkaas", "Chocolade", "Framboos"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Sesamzaad", "Gerst", "Haver", "Spelt", "Rogge",
                            "Amandel", "Cashewnoot", "Hazelnoot", "Pecannoot",
                            "Pistachenoot", "Walnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "red_velvet_muffin.png"),
        },
        "Carrot Cake Plak": {
            "category": "Sweets",
            "program": 15,
            "nasa": 789047,
            "price": 1.59,
            "type": [],
            "tags": ["Glazuur", "Walnoot"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Noten", "Glutenbevattende Granen"],
            "may_contain": ["Haver", "Spelt", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Macadamianoot", "Pecannoot", "Paranoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "carrot_cake_plak.png"),
        },
        "Rocky Road Cake": {
            "category": "Sweets",
            "program": 15,
            "nasa": 810795,
            "price": 0.99,
            "type": [],
            "tags": ["Chocolade", "Karamel", "Glazuur", "Hazelnoot"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Glutenbevattende Granen", "Soja",
                         "Lactose", "Tarwe"],
            "may_contain": ["Noten", "Pinda's", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Pecannoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "rocky_road_cake.png"),
        },
        "Carrot Cake": {
            "category": "Sweets",
            "program": 15,
            "nasa": 810805,
            "price": 0.99,
            "type": [],
            "tags": ["Glazuur", "Walnoot"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Noten", "Glutenbevattende Granen",
                         "Lactose", "Walnoot", "Tarwe"],
            "may_contain": ["Pinda's", "Soja", "Amandel", "Cashewnoot", "Hazelnoot",
                            "Pecannoot", "Pistachenoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "carrot_cake.png"),
        },
        "Kersen Cake": {
            "category": "Sweets",
            "program": 15,
            "nasa": 843987,
            "price": 0.99,
            "type": [],
            "tags": ["Banketbakkers room", "Kersen", "Amandel"],
            "rack_type": None,
            "per_rack": None,
            "defrost_time": None,
            "cooldown_time": None,
            "make_halves": None,
            "vegan": False,
            "contains": ["Eieren", "Melk", "Noten", "Glutenbevattende Granen", "Lactose",
                         "Amandel", "Tarwe"],
            "may_contain": ["Soja", "Hazelnoot", "Pecannoot", "Pistachenoot", "Walnoot"],
            "image": os.path.join(SWEETS_IMAGES_FOLDER,
                                  "kersen_cake.png"),
        },
    }
    return data


def get_bakery_dict() -> dict:
    dict_ = {}
    dict_.update(get_lp_bread_dict())
    dict_.update(get_stevig_bread_dict())
    dict_.update(get_vloer_bread_dict())
    dict_.update(get_small_bread_dict())
    dict_.update(get_savory_dict())
    dict_.update(get_stokbrood_dict())
    dict_.update(get_pastry_dict())
    dict_.update(get_sweets_dict())
    return dict_


if __name__ == "__main__":
    pass
    # for item, details in get_bakery_dict().items():
    #     image_path = details.get("image")
    #     if image_path:
    #         if not os.path.exists(image_path):
    #             print(f"{item}: {image_path} FAILED")
